service: cap-xml

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  role: ${env:SLS_LAMBA_ROLE}
  stage: ${env:TARGET_ENV_NAME}
  region: ${env:TARGET_REGION}
  deploymentBucket:
    name: ${env:SLS_BUCKET}
  vpc:
    securityGroupIds:
      - ${env:SLS_VPN_SECURITY_GROUP}
    subnetIds:
      - ${env:SLS_SUBNET_1}
      - ${env:SLS_SUBNET_2}
package:
 exclude:
   - test
functions:
  processMessage:
    handler: lib/functions/processMessage.processMessage
  getMessages:
    handler: lib/functions/getMessages.getMessages
